# Generated by Django 4.2.7 on 2025-03-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0002_consultant_cv_alter_document_fichier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='cv',
        ),
    ]
